namespace Itca.Api.Features.Applications;

public sealed record ApplicationProgressDto(
    string ApplicationNo,
    string? MemberNo,
    string ApplicationType,
    string Name,
    string Status,
    string AdminNote,
    string? MemberValidFrom,
    string? MemberValidUntil,
    string? MemberEffectiveStatus,
    string? MemberEffectiveStatusLabel,
    string? CertificateNo,
    string? CertificateDetailUrl,
    string? CertificateStatus,
    string? CertificateReviewStatus,
    string? CertificateEffectiveStatus,
    string? CertificateEffectiveStatusLabel,
    string? CertificateHolderName,
    string? CertificateTaoistName,
    string? CertificationPath,
    string? CertificationLevel,
    string? CertificateLineageOrTemple,
    string? CertificateIssuer,
    string? CertificateIssuedDate,
    string? CertificateValidFrom,
    string? CertificateValidUntil,
    bool? CertificatePhotoRecorded,
    string? DeliveryStatus,
    string? DeliveredAt,
    string? SupplementSubmittedAt,
    bool HasSupplementalSubmission,
    IReadOnlyDictionary<string, string>? EditableData,
    string CreatedAt,
    string UpdatedAt
);
